name: adb_tool
description: A simple ADB 工具箱桌面应用
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  process_run: ^0.13.2
  shared_preferences: ^2.2.2
  path: ^1.8.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true